spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: adeda249321077b1ea78f8f04428cf4f
  mail:
    password: NEED_TO_INPUT
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname
  jwt:
    secretKey: "12312jj12rjfjioofdsjk1212jkjkf1if3i1i32fni23u2if23ofof1if1331312fewc2211nuh188199e28"  # JWT 비밀 키 설정
    expirationTime: 3600000  # JWT 만료 시간 (1시간)
