spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: adeda249321077b1ea78f8f04428cf4f
  mail:
    password: nnrj mnfe ubyo zlqb
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname
  jwt:
    secretKey: "12312jj12rjfjioofdsjk1212jkjkf1if3i1i32fni23u2if23ofof1if1331312fewc2211nuh188199e28"  # JWT 비밀 키 설정
    expirationTime: 3600000  # JWT 만료 시간 (1시간)

korea-investment:
  token-url: "https://openapi.koreainvestment.com:9443/oauth2/tokenP"
  api-key: "PSlBkPCX0esNWc5Tv1vDYh37FZnf6BPlEACX"  # 실제 한국투자증권 API 키로 변경
  secret-key: "ucJXLQefoLvC3ObryidOsMBx/DF50MpaKYArOCcyfGStu0og5psl4oR60B2sI55RM9slwmPN/tDvKGS0k+R+1eGR4N4lWltyMtG9DnV1/GLB8h69vcMpm3uHd8EoY5wHGMidM11wblylmKAv3hc+jcyHFe+yyF4BBAhqxwHMaxNoNLpFEd0="  # 실제 한국투자증권 Secret 키로 변경
  base-url: "https://openapi.koreainvestment.com:9443"  # 한국투자증권 API Base URL